### ISSUE TITLE
Coverity flags possible race condition

### ISSUE THREAD

**Issue by wa4otj** [miconda/rtpproxy#2]
/rtpproxy-master/rtpp_syslog_async.c:  Playing with rtpproxy and coverity, coverity flags a possible race condition with the following error message:

Line 100: Value not atomically updated - Concurrent data access violations - Using an unreliable value of "wi" inside the second locked section. If the data that "wi" depends on was changed by another thread, this use might be incorrect.

I am not suggesting there is necessarily a problem, and I am not making a bug report. Merely passing along an observation.

**Comment by miconda** [comment]
Closing, this fork was merged into mainstream rtpproxy 2.0, any issue should be reported there.
