### ISSUE TITLE
code flow of rtpproxy

### ISSUE THREAD

**Issue by Dpkpadhy** [miconda/rtpproxy#3]
hey Mic, installed the rtpproxy and works as expected. To add new features , needed to go through the code flow of rtp proxy using GDB.

Though i am digging into this, need your help to understand how GDB tool will work for rtp proxy, basically i tried by this 

gdb /usr/local/bin/rtpproxy <pid>  

with this though i can see the stack trace but the breakpoints are not hitting. 

So to summarize, when a call is made through rtpproxy, it should hit the breakpoints in gdb so that i can see all of it code flow. Need your help on this.

**Comment by miconda** [comment]
Closing, this fork was merged into mainstream rtpproxy 2.0, any issue should be reported there.
